import turtle
turtle.bgcolor("green")
t=turtle.Turtle()
turtle.speed(0)
t.color("red")
t.begin_fill()
t.fillcolor("purple")
t.left(140)
t.forward(180)
t.circle(-90,200)
t.setheading(60)
t.circle(-90,200)
t.forward(180)
t.end_fill()
turtle.done()
#turtle.getscreen()._root.mainloop()